<?php
/*
 * This file was autogenerated
*/
$conf['email']['smtp'] = 'email-smtp.eu-west-1.amazonaws.com';
$conf['email']['port'] = 587;
$conf['email']['username'] = 'AKIAJVUPCWFEKKVOQI5A';
$conf['email']['password'] = 'AtOiLA3ORc/aS8cSBtQxC7iIYZICYXzHgwv/RkYi4j1j';
$conf['email']['auth'] = 'tls';
$conf['email']['defaultEmail'] = 'redazione@biologiawiki.it';
$conf['email']['defaultEmailName'] = 'BiologiaWiki';
$conf['email']['replyEmail'] = 'noreply@biologiawiki.it';
$conf['email']['replyEmailName'] = 'BiologiaWiki.it / no-reply';
$conf['email']['enableEmail'] = true; // Set false to *global* disable emails, this affects onyl FabCMS
$conf['email']['bypassVerifyPeer'] = true;