<?php
$theData = $conf['path']['baseDir'] . 'modules/singlepage/data.php';
$thePage = $conf['path']['baseDir'] . 'modules/singlepage/singlepage.html';

if (isset($_GET['save'])) {
    if (!isset($_POST['dummy'])) {
        echo 'Reload detected. You are safe!';
    } else {
        $title = htmlentities($_POST['title'], ENT_QUOTES);
        $description = htmlentities($_POST['description'], ENT_QUOTES);
        $html = $_POST['html'];

        $theDataContent =
            <<<EOT
            <?php
/* This file is autogenerated */
\$conf['singlepage']['title'] = '{$title}';
\$conf['singlepage']['description'] = '{$description}';
EOT;

        if (file_put_contents($thePage, $html)) {
            echo $template->getCustomBox(['title'   => 'Page update status',
                                          'message' => 'Page was updated',
                                          'class' => 'success']);
        } else {
            echo $template->getCustomBox(['title'   => 'Error updating status',
                                          'message' => 'Page was not updated',
                                          'class' => 'danger']);
        }


        if (file_put_contents($theData, $theDataContent)) {
            echo $template->getCustomBox(['title'   => 'Page update status',
                                          'message' => 'Page was updated',
                                          'class' => 'success']);
        } else {
            echo $template->getCustomBox(['title'   => 'Error updating status',
                                          'message' => 'Page was not updated',
                                          'class' => 'danger']);
        }
    }
}

if (!file_exists($thePage)) {
    echo $template->getCustomBox(['title'   => 'Custom page status',
                                  'message' => 'Custom page doesn\'t exists. Singlepage has no custom HTML.',
                                  'class' => 'info']);

} else {
    $html = file_get_contents($thePage);
}

if (!file_exists($theData)) {
    echo $template->getCustomBox(['title'   => 'Custom data status',
                                  'message' => 'Custom data doesn\'t exists. Singlepage has no custom data.',
                                  'class' => 'info']);


} else {
    include $theData;
}

echo '
<h1>Singlepage control</h1>
<form action="admin.php?module=singlepage&save" method="post">
  <input type="hidden" id="dummy" name="dummy" />

  <div class="form-group">
    <label for="title" class="col-sm-2 control-label">Title</label>
    <div class="col-sm-10">
      <input type="text" class="form-control" name="title" id="title" placeholder="Title" value="' . $conf['singlepage']['title'] . '">
    </div>
  </div>

  <div class="form-group">
    <label for="description" class="col-sm-2 control-label">Description</label>
    <div class="col-sm-10">
      <input type="text" class="form-control" name="description" id="description" placeholder="Description" value="' . $conf['singlepage']['description'] . '">
    </div>
  </div>

  <div class="form-group">
    <label for="html" class="col-sm-2 control-label">
        HTML code
    </label>
    <div class="col-sm-10">
      <textarea class="form-control" name="html" id="html_textarea" placeholder="Custom code here">' . $html . '</textarea>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-default">Update</button>
    </div>
  </div>
</form>


<script src="' . $URI->getBaseUri(true) . '/lib/codemirror/lib/codemirror.js"></script>
<link rel="stylesheet" href="' . $URI->getBaseUri(true) . '/lib/codemirror/lib/codemirror.css">

<script src="' . $URI->getBaseUri(true) . '/lib/codemirror/mode/xml/xml.js"></script>

<script>
      var editor = CodeMirror.fromTextArea(document.getElementById("html_textarea"), {
        mode: {name: "xml", alignCDATA: true},
        lineNumbers: true
      });

      $("btnSend").button();
</script>
';